version: '3'
volumes:
    portainer_data:
services:
    Jupyter:
        image: asolega/mid-term
        volumes:
            - /home/ubuntu/review/Mid-term/work:/home/jovyan/work
        ports:
            - 80:8888
    portainer:
        image: portainer/portainer
        volumes:
            -  /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9000:9000
